### PR TITLE
Implement MIN function

### PR DESCRIPTION
**Pull request by palango**
Low hanging fruit from #37.

### CODE REVIEW

**Comment by sgrif** [comment]
The added test is failing. You need to add this as a re-export in `expression::dsl`. This also could use an integration test, and a changelog entry.

**Comment by palango** [comment]
How can I run the compile-fail tests? If I run `cargo test` in the `diesel` and `diesel_test` directories I only get green tests.

**Comment by sgrif** [comment]
To test nightly only features, you need to do `cargo test --no-default-features --features unstable` in `diesel_test`. Or just run `bin/test` from the root directory. I should put this in a `CONTRIBUTING.md` now that I think about it.

**Comment by palango** [comment]
Should I squash the commits?

**Comment by sgrif** [comment]
Thanks!

**Pull request merged**
