### PR TITLE
Build on the latest nightly again

### PR DESCRIPTION
**Pull request by mcasper**
Updates various dependencies affected by
https://github.com/rust-lang/rust/pull/29850.

Opening so that other people won't have to duplicate this work, once
https://github.com/slapresta/rust-dotenv/pull/27 is merged I'll update
the dependency and this can go in.

### CODE REVIEW

**Comment by mfpiccolo** [comment]
@mcasper Nicely done.  I was just looking into this and saw your PR here and at rust-dotenv.

**Comment by mfpiccolo** [comment]
Looks good but we have to change travis config

**Comment by mcasper** [comment]
Was about to ask about that. Just update the ` nightly-2015-12-03` entry, or update to today?

**Comment by mfpiccolo** [comment]
I was thinking just remove it but I am not sure if we have to revert the other config Sean added

**Comment by mcasper** [comment]
I'm assuming allowing failures on `nightly` is to try and get a glimpse of future breakages, so let's see what happens if we bump the date stamped version.

**Comment by mcasper** [comment]
Looks like that did the trick!

**Comment by mfpiccolo** [comment]
:tada:

**Comment by mfpiccolo** [comment]
Thank you!   I was just looking into this here and at dotenv when I saw your PRs come in.

**Pull request merged**
