### PR TITLE
documentation fix of function `diesel::update`

### PR DESCRIPTION
**Pull request by benaryorg**

### CODE REVIEW

**Comment by benaryorg** [comment]
I'm sorry, I just noticed something else related to the documentation and fixed it. That wasn't a typo so I thought closing, and reopening with a new title might be the better idea.

**Comment by sgrif** [comment]
Can you squash these commits?

**Comment by benaryorg** [comment]
If by "squashing" you mean unifying them into one commit, yes I can.

**Comment by mcasper** [comment]
Thanks for this!

**Pull request merged**
