### PR TITLE
Bump syntex and syntex_syntax to 0.30.0

### LINKED ISSUE #241: Increment Syntex Version to 0.30.0
Would it be possible to increment the syntex version to 0.30.0 so that I can use Diesel with serde_codegen?

### PR DESCRIPTION
**Pull request by mcasper**
Resolves #241

### CODE REVIEW

**Comment by sgrif** [comment]
Should this be `>= 28.0.0, < 30.1.0`?

**Comment by mcasper** [comment]
Yeah I think that'd work, I'll update this real quick

**Comment by sgrif** [comment]
Cool. Was about to push the same, but if you can update this I'd like to see a green CI run. I've updated dotenv master

**Comment by mcasper** [comment]
@sgrif We're good to go

**Pull request merged**
